# Generated by Django 5.1.4 on 2024-12-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('anime', 'Anime'), ('book', 'Book'), ('manga', 'Manga'), ('music', 'Music'), ('video_game', 'Video Game'), ('todo_list', 'Todo List')], max_length=10)),
                ('apiUrl', models.URLField(choices=[('https://api.themoviedb.org/3/search/movie', 'Movie'), ('https://api.themoviedb.org/3/search/tv', 'Tv Show'), ('http://animedb.me/api/shows/title', 'Anime'), ('https://api2.isbndb.com/books/', 'Book'), ('manga', 'Manga'), ('https://musicbrainz.org/ws/2/', 'Music'), ('video_game', 'Video Game'), ('NOT NEEDED', 'Todo List')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.category')),
            ],
        ),
    ]
