# Generated by Django 5.1.4 on 2025-01-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_apiurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='apiUrl',
            field=models.URLField(choices=[('https://api.themoviedb.org/3/search/movie', 'Movie API'), ('https://api.themoviedb.org/3/search/tv', 'TV Show API'), ('http://animedb.me/api/shows/title', 'Anime API'), ('https://api2.isbndb.com/books/', 'Book API'), ('manga', 'Manga API'), ('https://musicbrainz.org/ws/2/', 'Music API'), ('video_game', 'Video Game API'), ('NOT NEEDED', 'No API Needed')]),
        ),
    ]
