# Generated by Django 5.1.4 on 2025-01-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_apiurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='apiUrl',
        ),
    ]
