# Generated by Django 5.1.4 on 2025-01-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_category_apiurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
