# Generated by Django 5.1.4 on 2025-01-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_info',
        ),
    ]
