# Generated by Django 5.1.4 on 2025-01-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_item_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_info',
        ),
    ]
