# Generated by Django 5.1.4 on 2025-01-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_item_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_grade',
            field=models.IntegerField(null=True),
        ),
    ]
