# Generated by Django 5.1.4 on 2025-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_item_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_description',
            field=models.TextField(blank=True),
        ),
    ]
